// AUTO-GENERATED UI phrase dictionary (uz -> ru/en). Manba matn = o'zbekcha.
export const PHRASES: Record<string, {
  "Tema": { ru: "Тема", en: "Theme" },
  "Tema saqlandi": { ru: "Тема сохранена", en: "Theme saved" }, ru: string; en: string }> = {
  "Admin Tasdiqlangan": { ru: "Подтверждено админом", en: "Admin Approved" },
  "Admin bilan bog‘lanish": { ru: "Связаться с админом", en: "Contact Admin" },
  "Admin ko‘rigiga yuborish": { ru: "Отправить на проверку админу", en: "Send for Admin Review" },
  "Admin ma’lumot va media fayllarni tekshiradi.": { ru: "Админ проверит информацию и медиафайлы.", en: "Admin will check information and media files." },
  "Admin panelida dispute resolution, e’lon tekshiruvi va yechib olish so‘rovlarini navbat bilan boshqaring.": { ru: "В панели админа управляйте разрешением споров, проверкой объявлений и запросами на вывод средств по очереди.", en: "In the admin panel, manage dispute resolution, listing review, and withdrawal requests sequentially." },
  "Admin tasdiqlagach summa balansga qo‘shiladi (odatda 5–30 daqiqa).": { ru: "После подтверждения админом сумма будет добавлена на баланс (обычно 5–30 минут).", en: "Once approved by admin, the amount will be added to the balance (usually 5–30 minutes)." },
  "Admin tekshiruvidan o‘tmadi.": { ru: "Не прошел проверку админом.", en: "Failed Admin Review." },
  "Agar do‘stingiz kod bergan bo‘lsa, uni bir marta shu yerda kiriting.": { ru: "Если ваш друг дал вам код, введите его здесь один раз.", en: "If your friend gave you a code, enter it here once." },
  "Akkaunt ID": { ru: "ID аккаунта", en: "Account ID" },
  "Akkaunt ID, skin yoki o'yinchi nomini qidiring...": { ru: "Ищите ID аккаунта, скин или имя игрока...", en: "Search Account ID, skin, or player name..." },
  "Akkaunt Sotish": { ru: "Продать аккаунт", en: "Sell Account" },
  "Akkaunt Tafsilotlari": { ru: "Детали аккаунта", en: "Account Details" },
  "Akkaunt galereyasi": { ru: "Галерея аккаунта", en: "Account gallery" },
  "Akkaunt haqida to‘liq ma’lumot va media qo‘shing. Rasm va videolar xavfsiz S3 xotirasiga yuboriladi.": { ru: "Добавьте полную информацию и медиа об аккаунте. Фото и видео будут загружены в безопасное S3 хранилище.", en: "Add full account info and media. Photos and videos will be uploaded to secure S3 storage." },
  "Akkaunt ochilgan yil 2008–2030 oralig‘ida bo‘lishi kerak.": { ru: "Год создания аккаунта должен быть в диапазоне 2008–2030.", en: "Account creation year must be between 2008–2030." },
  "Akkaunt rasm va videolarini xarid oldidan diqqat bilan tekshiring.": { ru: "Внимательно проверьте фото и видео аккаунта перед покупкой.", en: "Carefully check account photos and videos before purchase." },
  "Akkaunt saqlanganlar ro‘yxatiga qo‘shildi": { ru: "Аккаунт добавлен в избранное", en: "Account added to favorites" },
  "Akkaunt saqlanganlardan olib tashlandi": { ru: "Аккаунт удален из избранного", en: "Account removed from favorites" },
  "Akkaunt sotish": { ru: "Продажа аккаунта", en: "Sell Account" },
  "Akkaunt sotish uchun Telegram orqali kiring": { ru: "Войдите через Telegram, чтобы продать аккаунт", en: "Log in via Telegram to sell account" },
  "Akkaunt tekshirilmoqda": { ru: "Аккаунт проверяется", en: "Account under review" },
  "Akkaunt tekshiruvi": { ru: "Проверка аккаунта", en: "Account review" },
  "Akkaunt topilmadi": { ru: "Аккаунт не найден", en: "Account not found" },
  "Akkaunt yuklanmoqda...": { ru: "Аккаунт загружается...", en: "Account loading..." },
  "Akkauntlar bozori": { ru: "Маркет аккаунтов", en: "Account Marketplace" },
  "Akkauntlar yuklanmoqda...": { ru: "Аккаунты загружаются...", en: "Accounts loading..." },
  "Akkauntlarni ko'rish": { ru: "Просмотр аккаунтов", en: "View accounts" },
  "Akkauntni qabul qilgach 24 soat ichida tasdiqlang, aks holda avtomatik yopiladi.": { ru: "Подтвердите получение аккаунта в течение 24 часов, иначе сделка закроется автоматически.", en: "Confirm account receipt within 24 hours, otherwise it will close automatically." },
  "Aniq statistika, inventar ro'yxati va sifatli media xaridor savollarini kamaytiradi.": { ru: "Точная статистика, список инвентаря и качественные медиа уменьшают вопросы покупателей.", en: "Accurate stats, inventory list, and quality media reduce buyer questions." },
  "Arizalar yuklanmoqda...": { ru: "Заявки загружаются...", en: "Applications loading..." },
  "Audit yozuvlari yo‘q": { ru: "Нет записей аудита", en: "No audit records" },
  "Avval balansingizni to‘ldiring, so‘ng akkauntni sotib oling.": { ru: "Сначала пополните баланс, затем купите аккаунт.", en: "First top up your balance, then buy the account." },
  "Balans karta orqali to‘ldiriladi: karta raqamiga o‘tkazing va chek rasmini yuboring.": { ru: "Баланс пополняется через карту: переведите на номер карты и отправьте фото чека.", en: "Balance is topped up via card: transfer to card number and send a photo of the receipt." },
  "Balans to‘ldirildi": { ru: "Баланс пополнен", en: "Balance topped up" },
  "Balans to‘ldirish": { ru: "Пополнить баланс", en: "Top up balance" },
  "Balans to‘ldirish, yechib olish, payout va barcha moliyaviy harakatlar faqat Telegram profilingizga ulanadi.": { ru: "Пополнение баланса, вывод средств, выплаты и все финансовые операции привязаны только к вашему профилю Telegram.", en: "Balance top-up, withdrawals, payouts, and all financial actions are linked only to your Telegram profile." },
  "Balans to‘ldirish, yechib olish, payout va boshqa moliyaviy harakatlaringizni bir joyda kuzating.": { ru: "Отслеживайте пополнение баланса, вывод средств, выплаты и другие финансовые операции в одном месте.", en: "Track your balance top-ups, withdrawals, payouts, and other financial activities in one place." },
  "Barcha foydalanuvchilarga in-app xabar yuboring.": { ru: "Отправить сообщение всем пользователям в приложении.", en: "Send in-app message to all users." },
  "Barcha foydalanuvchilarga yuborish": { ru: "Отправить всем пользователям", en: "Send to all users" },
  "Barcha maydonlarni to‘ldiring": { ru: "Заполните все поля", en: "Fill in all fields" },
  "Barchasi o‘qilgan": { ru: "Все прочитано", en: "All read" },
  "Ba’zi ma’lumotlar yuklanmadi. Internetni tekshirib, sahifani qayta oching.": { ru: "Некоторые данные не загрузились. Проверьте интернет и обновите страницу.", en: "Some data didn't load. Check your internet and refresh the page." },
  "Bekor qilindi": { ru: "Отменено", en: "Canceled" },
  "Bekor qilish": { ru: "Отменить", en: "Cancel" },
  "Bildirishnoma o‘chirildi": { ru: "Уведомление удалено", en: "Notification deleted" },
  "Bildirishnomalarni ko‘rish uchun profilga kiring.": { ru: "Войдите в профиль, чтобы просмотреть уведомления.", en: "Log in to your profile to view notifications." },
  "Birinchi akkauntingizni bozorga qo‘ying.": { ru: "Разместите свой первый аккаунт на маркете.", en: "List your first account on the marketplace." },
  "Birinchi e’lonni joylash": { ru: "Разместить первое объявление", en: "Post first listing" },
  "Birinchi xabarni yuboring.": { ru: "Отправьте первое сообщение.", en: "Send your first message." },
  "Bitim bo‘yicha barcha suhbatlar shu yerda.": { ru: "Все чаты по сделке здесь.", en: "All transaction chats are here." },
  "Bitim, to‘lov va chat yangiliklarini ko‘rish uchun tizimga kiring.": { ru: "Войдите в систему, чтобы просматривать обновления по сделкам, платежам и чатам.", en: "Log in to see transaction, payment, and chat updates." },
  "Boshqa foydalanuvchini haqorat qilish yoki spam yuborish.": { ru: "Оскорбление другого пользователя или отправка спама.", en: "Insulting another user or sending spam." },
  "Bozor hozircha bo‘sh": { ru: "Маркет пока пуст", en: "Market is empty for now" },
  "Bozor ko‘rinishini tanlang": { ru: "Выберите вид маркета", en: "Select market view" },
  "Bozorda darhol ko‘rinadi": { ru: "Будет сразу видно на маркете", en: "Immediately visible on the market" },
  "Bozorda yurakcha tugmasini bosib akkaunt saqlang.": { ru: "Сохраните аккаунт, нажав на сердечко на маркете.", en: "Save an account by clicking the heart button on the market." },
  "Bozorga joylash": { ru: "Разместить на маркете", en: "Post to market" },
  "Bozorga kirish": { ru: "Войти на маркет", en: "Enter market" },
  "Bozorga o'tish": { ru: "Перейти на маркет", en: "Go to market" },
  "Bozorga qaytish": { ru: "Вернуться на маркет", en: "Return to market" },
  "Bozorni ko‘rish": { ru: "Посмотреть маркет", en: "View market" },
  "Bu bo‘lim faqat platforma egasi va adminlar uchun ochiq.": { ru: "Этот раздел открыт только для владельца платформы и администраторов.", en: "This section is only open to the platform owner and admins." },
  "Buyurtma holati yangilandi": { ru: "Статус заказа обновлен", en: "Order status updated" },
  "Buyurtma raqamini to‘g‘ri kiriting": { ru: "Введите правильный номер заказа", en: "Enter correct order number" },
  "Buyurtma to‘lovi": { ru: "Оплата заказа", en: "Order payment" },
  "Buyurtma yuklanmoqda...": { ru: "Заказ загружается...", en: "Order loading..." },
  "Buyurtmalar topilmadi": { ru: "Заказы не найдены", en: "Orders not found" },
  "Buyurtmalar yuklanmoqda...": { ru: "Заказы загружаются...", en: "Orders loading..." },
  "Buyurtmalarni ko‘rish": { ru: "Просмотреть заказы", en: "View orders" },
  "Chatlar yuklanmoqda...": { ru: "Чаты загружаются...", en: "Chats loading..." },
  "Chek admin tekshiruviga yuborildi": { ru: "Чек отправлен на проверку админу", en: "Receipt sent for admin review" },
  "Chek ma’lumotlari mos kelmadi.": { ru: "Данные чека не совпали.", en: "Receipt data did not match." },
  "Chek qarori saqlandi": { ru: "Решение по чеку сохранено", en: "Receipt decision saved" },
  "Chekni adminlarga yuborish": { ru: "Отправить чек админам", en: "Send receipt to admins" },
  "Chekni yuborishda xatolik yuz berdi": { ru: "Произошла ошибка при отправке чека", en: "An error occurred while sending the receipt" },
  "Daraja 1 dan 100 gacha bo‘lishi kerak.": { ru: "Уровень должен быть от 1 до 100.", en: "Level must be between 1 and 100." },
  "Daraja, mintaqa, skin va narx bo'yicha kerakli akkauntni toping.": { ru: "Найдите нужный аккаунт по уровню, региону, скинам и цене.", en: "Find the desired account by level, region, skins, and price." },
  "Deposit va payout qarorlari kim tomonidan va qachon bajarilganini ko‘ring.": { ru: "Посмотрите, кем и когда были выполнены решения по депозитам и выплатам.", en: "See who and when made deposit and payout decisions." },
  "Do‘stingizni taklif qiling": { ru: "Пригласите друга", en: "Invite your friend" },
  "Do‘stlaringizni taklif qiling": { ru: "Пригласите друзей", en: "Invite friends" },
  "Do‘stlaringizni taklif qilish va bonus olish uchun tizimga kiring.": { ru: "Войдите, чтобы пригласить друзей и получить бонус.", en: "Log in to invite friends and get a bonus." },
  "E'lon bozorga joylandi": { ru: "Объявление размещено на рынке", en: "Ad posted to marketplace" },
  "E'lon yuboriladi": { ru: "Объявление отправляется", en: "Ad is being sent" },
  "E'lonlar darhol xaridorlarga ko‘rinadi": { ru: "Объявления сразу видны покупателям", en: "Ads are immediately visible to buyers" },
  "Edit profile": { ru: "Редактировать профиль", en: "Edit profile" },
  "Elite sotuvchi": { ru: "Элитный продавец", en: "Elite seller" },
  "Eng yaxshi akkauntlarni topish va sotish": { ru: "Найти и продать лучшие аккаунты", en: "Find and sell the best accounts" },
  "Escrow checkout uchun kamida bitta to‘lov provayderini sozlash kerak.": { ru: "Для Escrow-оплаты должен быть настроен хотя бы один провайдер.", en: "At least one payment provider must be configured for Escrow checkout." },
  "Eski akkaunt": { ru: "Старый аккаунт", en: "Old account" },
  "E’lon berish uchun avval tizimga kiring.": { ru: "Чтобы подать объявление, сначала войдите.", en: "To post an ad, please log in first." },
  "E’lon qo‘yilgach ommaviy bozorga chiqadi. Narx, tavsif va asosiy ma’lumotlarni istalgan vaqtda tahrirlashingiz mumkin.": { ru: "Объявление будет размещено на публичном рынке. Вы можете редактировать цену, описание и основные данные в любое время.", en: "Your ad will be posted to the public marketplace. You can edit the price, description, and key details at any time." },
  "E’lon saqlanmoqda...": { ru: "Объявление сохраняется...", en: "Ad is being saved..." },
  "E’lon yangilandi va bozorda ko‘rinishi davom etadi.": { ru: "Объявление обновлено и будет продолжать отображаться на рынке.", en: "Ad has been updated and will continue to be visible on the marketplace." },
  "E’longa kamida 3 ta rasm va 1 ta video biriktiring.": { ru: "Прикрепите минимум 3 фото и 1 видео к объявлению.", en: "Attach at least 3 photos and 1 video to the ad." },
  "E’loningiz ommaviy bozorga joylandi.": { ru: "Ваше объявление размещено на публичном рынке.", en: "Your ad has been posted to the public marketplace." },
  "E’lonlar yuklanmoqda...": { ru: "Объявления загружаются...", en: "Loading ads..." },
  "E’lonni saqlashda xatolik yuz berdi.": { ru: "Произошла ошибка при сохранении объявления.", en: "An error occurred while saving the ad." },
  "E’lonni yuborishda xatolik yuz berdi.": { ru: "Произошла ошибка при отправке объявления.", en: "An error occurred while sending the ad." },
  "FAQ qo‘shildi": { ru: "FAQ добавлен", en: "FAQ added" },
  "FAQ yuklanmoqda...": { ru: "Загрузка FAQ...", en: "Loading FAQ..." },
  "Faol e’lon": { ru: "Активное объявление", en: "Active ad" },
  "Faqat JPG, PNG, WEBP, MP4, MOV yoki WEBM fayllari qabul qilinadi.": { ru: "Принимаются только файлы JPG, PNG, WEBP, MP4, MOV или WEBM.", en: "Only JPG, PNG, WEBP, MP4, MOV, or WEBM files are accepted." },
  "Faqat haqiqiy sotuvchilar e’lonlari chiqadi.": { ru: "Будут показаны только объявления реальных продавцов.", en: "Only ads from verified sellers will be displayed." },
  "Faqat yakunlangan savdolar uchun": { ru: "Только для завершенных сделок", en: "Only for completed sales" },
  "Fayl o‘qilmadi": { ru: "Файл не прочитан", en: "File not read" },
  "Faylni o‘qib bo‘lmadi": { ru: "Не удалось прочитать файл", en: "Could not read file" },
  "Filtr oynasini yopish": { ru: "Закрыть окно фильтров", en: "Close filter window" },
  "Filtrlarni o'zgartirib ko'ring yoki keyinroq qaytib ko'ring.": { ru: "Попробуйте изменить фильтры или вернитесь позже.", en: "Try changing the filters or check back later." },
  "Filtrlarni qo‘llash": { ru: "Применить фильтры", en: "Apply filters" },
  "Foydalanuvchi sharh haqida xabar berganda shu yerda ko‘rinadi.": { ru: "Когда пользователь сообщает о комментарии, он отображается здесь.", en: "When a user reports a comment, it appears here." },
  "Galereyani katta ko‘rish": { ru: "Посмотреть галерею крупным планом", en: "View gallery larger" },
  "Hal qilindi": { ru: "Решено", en: "Resolved" },
  "Hali baho yo‘q": { ru: "Еще нет оценок", en: "No ratings yet" },
  "Hali bildirishnomalar yo‘q.": { ru: "Уведомлений пока нет.", en: "No notifications yet." },
  "Hali e’lon yo‘q": { ru: "Пока нет объявлений", en: "No ads yet" },
  "Hali manual top-up so‘rovi yo‘q.": { ru: "Пока нет запросов на ручное пополнение.", en: "No manual top-up requests yet." },
  "Hali tranzaksiya yo‘q": { ru: "Нет транзакций", en: "No transactions yet" },
  "Hali yuborilgan chek yo‘q.": { ru: "Чеков пока нет.", en: "No checks sent yet." },
  "Hamyon balansi": { ru: "Баланс кошелька", en: "Wallet balance" },
  "Hamyon orqali balans to‘ldirsangiz yoki yechib olsangiz, tarix shu yerda paydo bo‘ladi.": { ru: "Если вы пополните или выведете баланс через кошелек, история появится здесь.", en: "If you top up or withdraw balance via wallet, the history will appear here." },
  "Har bir e’lon egasiga chiqishidan oldin tekshiriladi.": { ru: "Каждое объявление проверяется перед публикацией.", en: "Every ad is checked before going live to the owner." },
  "Har bir foydalanuvchi Telegram raqami orqali tasdiqlanadi.": { ru: "Каждый пользователь подтверждается через номер Telegram.", en: "Every user is verified via Telegram number." },
  "Har bir rasm 200 MB dan kichik bo‘lishi kerak.": { ru: "Каждое изображение должно быть меньше 200 МБ.", en: "Each image must be smaller than 200 MB." },
  "Har bir status o‘zgarishi buyurtmada saqlanadi.": { ru: "Каждое изменение статуса сохраняется в заказе.", en: "Every status change is saved in the order." },
  "Har bir yangi foydalanuvchi sizning kodingiz orqali kirsa, referral dasturi orqali bonus yig‘asiz.": { ru: "Каждый новый пользователь, вошедший по вашему коду, приносит вам бонус через реферальную программу.", en: "For every new user who registers with your code, you accumulate bonuses through the referral program." },
  "Holatni yangilab bo‘lmadi": { ru: "Не удалось обновить статус", en: "Could not update status" },
  "Hozircha bildirishnoma yo‘q.": { ru: "Пока нет уведомлений.", en: "No notifications yet." },
  "Hozircha ochiq nizo yo‘q. Muammo tug‘ilsa, har bir bitim bo‘yicha dalillar bilan murojaat qiling.": { ru: "Пока нет открытых споров. При возникновении проблемы обращайтесь с доказательствами по каждой сделке.", en: "No open disputes yet. If a problem arises, contact us with evidence for each transaction." },
  "Hozircha sharh qoldirish mumkin bo‘lgan yakunlangan buyurtma yo‘q.": { ru: "Пока нет завершенных заказов, по которым можно оставить отзыв.", en: "No completed orders to leave a review for yet." },
  "Hozircha tranzaksiyalar mavjud emas.": { ru: "Пока нет транзакций.", en: "No transactions available yet." },
  "Hozircha yangi bildirishnoma yo‘q.": { ru: "Пока нет новых уведомлений.", en: "No new notifications yet." },
  "Inferno Gold Market’da xavfsiz savdo qilish tartibi": { ru: "Порядок безопасной торговли на Inferno Gold Market", en: "Safe trading procedure on Inferno Gold Market" },
  "Ishonch profili, escrow, sotuvchi CRM va referral boshqaruvi uchun Telegram profilingizni ulang.": { ru: "Привяжите свой профиль Telegram для профиля доверия, эскроу, CRM продавца и управления рефералами.", en: "Link your Telegram profile for trust profile, escrow, seller CRM, and referral management." },
  "Ishonch profilingiz": { ru: "Ваш профиль доверия", en: "Your Trust Profile" },
  "Javob yuborildi": { ru: "Ответ отправлен", en: "Reply sent" },
  "Kafolat bosqichi yangilandi": { ru: "Этап гарантии обновлен", en: "Warranty stage updated" },
  "Kamida 3 ta rasm qo‘shing": { ru: "Добавьте как минимум 3 изображения", en: "Add at least 3 images" },
  "Karta ma’lumoti": { ru: "Данные карты", en: "Card details" },
  "Karta raqami yoki hamyon manzili": { ru: "Номер карты или адрес кошелька", en: "Card number or wallet address" },
  "Karta yoki hamyon ma’lumotini kiriting": { ru: "Введите данные карты или кошелька", en: "Enter card or wallet details" },
  "Kartaga tushgan to‘lov cheklarini tekshiring va balansni faqat bir marta kredit qiling.": { ru: "Проверьте чеки оплаты на карту и зачислите баланс только один раз.", en: "Check payment receipts to the card and credit the balance only once." },
  "Kategoriya qo‘shildi": { ru: "Категория добавлена", en: "Category added" },
  "Katta ko‘rish": { ru: "Просмотр в полный размер", en: "Large view" },
  "Kerakli akkauntni tezroq toping": { ru: "Быстрее найдите нужный аккаунт", en: "Find the desired account faster" },
  "Kod orqali ulashish uchun tayyor.": { ru: "Готово для обмена по коду.", en: "Ready to share by code." },
  "Kodni qo‘llash": { ru: "Применить код", en: "Apply code" },
  "Ko‘rib chiqilmoqda": { ru: "На рассмотрении", en: "Under review" },
  "Kutilayotgan ariza yo‘q": { ru: "Нет ожидающих заявок", en: "No pending applications" },
  "Kutilayotgan e’lonlar yo‘q": { ru: "Нет ожидающих объявлений", en: "No pending ads" },
  "Kutilayotgan shikoyat yo‘q": { ru: "Нет ожидающих жалоб", en: "No pending complaints" },
  "Kutilayotgan yechib olish so‘rovi yo‘q.": { ru: "Нет ожидающих запросов на вывод.", en: "No pending withdrawal requests." },
  "Login va parolni bu yerga yubormang. Faqat Telegram sessiyasi ishlatiladi.": { ru: "Не отправляйте логин и пароль сюда. Используется только сессия Telegram.", en: "Do not send login and password here. Only Telegram session is used." },
  "Login va parolni chatga yozish qat’iyan man etiladi.": { ru: "Строго запрещено писать логин и пароль в чат.", en: "Strictly forbidden to write login and password in the chat." },
  "Login va parolni chatga yozmang. Faqat savdo tafsilotlarini muhokama qiling.": { ru: "Не пишите логин и пароль в чат. Обсуждайте только детали сделки.", en: "Do not write login and password in the chat. Discuss only trade details." },
  "Login yuborildi — tekshirib tasdiqlang.": { ru: "Логин отправлен — проверьте и подтвердите.", en: "Login sent — check and confirm." },
  "Mablag‘ qaytarilishi yoki to‘lanishini qo‘lda tasdiqlang.": { ru: "Подтвердите возврат или оплату средств вручную.", en: "Manually confirm refund or payment of funds." },
  "Mablag‘ yechib olish": { ru: "Вывод средств", en: "Withdraw funds" },
  "Maksimal narx": { ru: "Максимальная цена", en: "Maximum price" },
  "Manual to‘lov": { ru: "Ручная оплата", en: "Manual payment" },
  "Masalan: Bugun barcha premium e’lonlar uchun komissiya kamaytirildi...": { ru: "Например: Сегодня комиссия для всех премиум-объявлений снижена...", en: "For example: Today, the commission for all premium ads has been reduced..." },
  "Mavzu kamida 4 ta belgidan iborat bo‘lsin.": { ru: "Тема должна содержать не менее 4 символов.", en: "Topic must be at least 4 characters." },
  "Ma’lumotlar tekshiruvdan o‘tmadi.": { ru: "Данные не прошли проверку.", en: "Data failed validation." },
  "Ma’lumotlar yuklanmoqda...": { ru: "Данные загружаются...", en: "Loading data..." },
  "Media fayllar": { ru: "Медиафайлы", en: "Media files" },
  "Media ko‘rib chiqildi": { ru: "Медиа просмотрено", en: "Media reviewed" },
  "Media yuklanmoqda...": { ru: "Медиа загружается...", en: "Loading media..." },
  "Mening e’lonlarim": { ru: "Мои объявления", en: "My listings" },
  "Mening profilim": { ru: "Мой профиль", en: "My profile" },
  "Minimal narx": { ru: "Минимальная цена", en: "Minimum price" },
  "Minimum withdrawal is 10,000 so'm.": { ru: "Минимальный вывод — 10 000 сум.", en: "Minimum withdrawal is 10,000 so'm." },
  "Moderatsiya navbati bo‘sh.": { ru: "Очередь модерации пуста.", en: "Moderation queue is empty." },
  "Mos tavsiya topilmadi. Filtrlarni sinab ko‘ring.": { ru: "Подходящих рекомендаций не найдено. Попробуйте фильтры.", en: "No suitable recommendations found. Try filters." },
  "Muhim savdo yangiliklari": { ru: "Важные новости торговли", en: "Important trade news" },
  "Murojaatlaringizni ko‘rish uchun Telegram orqali kiring.": { ru: "Войдите через Telegram, чтобы просмотреть свои обращения.", en: "Log in via Telegram to view your requests." },
  "Narx 0 yoki undan katta bo‘lishi kerak.": { ru: "Цена должна быть 0 или больше.", en: "Price must be 0 or greater." },
  "Narx tushishi alerti": { ru: "Оповещение о снижении цены", en: "Price drop alert" },
  "Nizo admin ko‘rigiga yuborildi": { ru: "Спор отправлен на рассмотрение админу", en: "Dispute sent for admin review" },
  "Nizo bo‘lsa": { ru: "При наличии спора", en: "If there is a dispute" },
  "Nizo yo‘q": { ru: "Нет споров", en: "No dispute" },
  "Nizo yuzaga kelsa, dalillar (screenshot, video) 24 soat ichida yuboriladi.": { ru: "При возникновении спора, доказательства (скриншот, видео) отправляются в течение 24 часов.", en: "In case of dispute, evidence (screenshot, video) must be submitted within 24 hours." },
  "Nizoni yopish": { ru: "Закрыть спор", en: "Close dispute" },
  "Noma'lum akkaunt": { ru: "Неизвестный аккаунт", en: "Unknown account" },
  "Nusxa olishda xatolik": { ru: "Ошибка при копировании", en: "Copy error" },
  "Ochiq murojaat yo‘q.": { ru: "Нет открытых обращений.", en: "No open requests." },
  "Ochiq nizo yo‘q": { ru: "Нет открытых споров", en: "No open disputes" },
  "Ommaviy bozor": { ru: "Публичный рынок", en: "Public marketplace" },
  "Owner tasdiqlangan": { ru: "Владелец подтвержден", en: "Owner confirmed" },
  "Oynani yopmang — fayllar xavfsiz S3 xotirasiga yuborilmoqda.": { ru: "Не закрывайте окно — файлы загружаются в безопасное хранилище S3.", en: "Do not close the window — files are being uploaded to secure S3 storage." },
  "O‘yinchi nomi": { ru: "Имя игрока", en: "Player name" },
  "O‘yinchi nomi kamida 2 ta belgidan iborat bo‘lsin.": { ru: "Имя игрока должно содержать не менее 2 символов.", en: "Player name must be at least 2 characters." },
  "PUBG akkaunt": { ru: "Аккаунт PUBG", en: "PUBG account" },
  "PUBG akkaunt ID sini kiriting.": { ru: "Введите ID аккаунта PUBG.", en: "Enter PUBG account ID." },
  "PUBG akkauntingiz uchun": { ru: "Для вашего аккаунта PUBG", en: "For your PUBG account" },
  "Payout holati saqlandi": { ru: "Статус выплаты сохранен", en: "Payout status saved" },
  "Payout navbati bo‘sh": { ru: "Очередь выплат пуста", en: "Payout queue is empty" },
  "Platformadan tashqarida to‘lov taklif qilish.": { ru: "Предложение оплаты вне платформы.", en: "Offering payment outside the platform." },
  "Pro ma’lumotlari sinxronlanmoqda...": { ru: "Синхронизация данных Pro...", en: "Syncing Pro data..." },
  "Profil ma’lumotlari": { ru: "Данные профиля", en: "Profile data" },
  "Profil orqali tahrirlanadi": { ru: "Редактируется через профиль", en: "Edited via profile" },
  "Profil yangilandi": { ru: "Профиль обновлен", en: "Profile updated" },
  "Profil yuklanmoqda...": { ru: "Профиль загружается...", en: "Profile loading..." },
  "Profile details": { ru: "Детали профиля", en: "Profile details" },
  "Profilga Telegram orqali kiring": { ru: "Войдите в профиль через Telegram", en: "Log in to profile via Telegram" },
  "Profilga kirish": { ru: "Войти в профиль", en: "Log in to profile" },
  "Profilingiz, media fayllaringiz va sotuvchi e’lonlaringiz xavfsiz Telegram sessiyasi bilan bog‘lanadi.": { ru: "Ваш профиль, медиафайлы и объявления продавца будут связаны с безопасной сессией Telegram.", en: "Your profile, media files, and seller listings will be linked to a secure Telegram session." },
  "Profilni saqlashda xatolik": { ru: "Ошибка при сохранении профиля", en: "Error saving profile" },
  "Profilni tahrirlash": { ru: "Редактировать профиль", en: "Edit profile" },
  "Pul yechish minimal summasi 10 000 so‘m.": { ru: "Минимальная сумма вывода 10 000 сум.", en: "Minimum withdrawal amount is 10 000 UZS." },
  "Qabul qilishni tasdiqlash": { ru: "Подтвердить получение", en: "Confirm receipt" },
  "Qayta ko‘rib chiqmoqchi bo‘lgan e’lonlaringiz bir joyda.": { ru: "Ваши объявления для пересмотра в одном месте.", en: "Your listings for review in one place." },
  "Qiziqqan akkauntlaringizni saqlash uchun profilga kiring.": { ru: "Войдите в профиль, чтобы сохранить интересующие аккаунты.", en: "Log in to profile to save accounts of interest." },
  "Qoidabuzarlik tasdiqlandi.": { ru: "Нарушение подтверждено.", en: "Violation confirmed." },
  "Qoidabuzarlik topilmadi.": { ru: "Нарушение не найдено.", en: "No violation found." },
  "Qoidalarni buzgan foydalanuvchi hisobi bloklanadi va balansi muzlatiladi.": { ru: "Аккаунт пользователя, нарушившего правила, будет заблокирован, а баланс заморожен.", en: "The account of a user who violated the rules will be blocked, and their balance frozen." },
  "Qo‘shimcha izoh yo‘q.": { ru: "Дополнительных комментариев нет.", en: "No additional comments." },
  "Rasmlarni yuklash": { ru: "Загрузить изображения", en: "Upload images" },
  "Ro‘yxat hozircha bo‘sh": { ru: "Список пока пуст", en: "The list is currently empty" },
  "Saqlangan akkaunt narxi o‘zgarsa, kuzatuv ro‘yxatida ko‘rsatiladi.": { ru: "Если цена сохраненного аккаунта изменится, это будет указано в списке наблюдения.", en: "If the price of a saved account changes, it will be shown in the watchlist." },
  "Saqlangan akkauntlar": { ru: "Сохраненные аккаунты", en: "Saved accounts" },
  "Saqlanganlar yuklanmoqda...": { ru: "Сохраненные загружаются...", en: "Saved items loading..." },
  "Saqlash uchun avval Telegram orqali tizimga kiring.": { ru: "Для сохранения сначала войдите через Telegram.", en: "To save, first log in via Telegram." },
  "Saqlash vaqtida xatolik yuz berdi": { ru: "Произошла ошибка при сохранении", en: "An error occurred while saving" },
  "Saqlashdan oldin maydonlarni tekshiring.": { ru: "Проверьте поля перед сохранением.", en: "Check fields before saving." },
  "Savdo boshlaganingizdan so‘ng buyurtmalar shu yerda ko‘rinadi.": { ru: "После начала торговли заказы будут видны здесь.", en: "Once you start trading, orders will appear here." },
  "Savdoni bitta markazdan boshqaring: ishonch, escrow, to‘lov va xaridorlar bilan aloqa doimo nazorat ostida.": { ru: "Управляйте торговлей из одного центра: доверие, эскроу, оплата и связь с покупателями всегда под контролем.", en: "Manage trading from one hub: trust, escrow, payments, and communication with buyers are always under control." },
  "Savol yuborish uchun Telegram orqali kiring.": { ru: "Для отправки вопроса войдите через Telegram.", en: "To send a question, log in via Telegram." },
  "Savolingiz yuborildi. Admin tez orada javob beradi.": { ru: "Ваш вопрос отправлен. Администратор скоро ответит.", en: "Your question has been sent. The admin will reply soon." },
  "Savollar bo'yicha admin bilan aloqa": { ru: "Связь с админом по вопросам", en: "Contact admin for questions" },
  "Savolni kamida 10 ta belgi bilan yozing.": { ru: "Напишите вопрос длиной не менее 10 символов.", en: "Write the question with at least 10 characters." },
  "Savolni yuborish": { ru: "Отправить вопрос", en: "Send question" },
  "Server xatosi": { ru: "Ошибка сервера", en: "Server error" },
  "Sharh qoldirish va sotuvchilar ishonchliligini ko‘rish uchun Inferno Stealth profiliga kiring.": { ru: "Войдите в профиль Inferno Stealth, чтобы оставить отзыв и посмотреть надежность продавцов.", en: "Log in to your Inferno Stealth profile to leave a review and view seller reliability." },
  "Sharh shikoyati adminlarga yuborildi": { ru: "Жалоба на отзыв отправлена администраторам", en: "Review complaint sent to admins" },
  "Sharh shikoyati bo‘yicha qaror saqlandi": { ru: "Решение по жалобе на отзыв сохранено", en: "Decision on review complaint saved" },
  "Sharhingiz saqlandi. Xarid tajribasi uchun rahmat!": { ru: "Ваш отзыв сохранен. Спасибо за опыт покупки!", en: "Your review has been saved. Thank you for your purchase experience!" },
  "Sharhni saqlashda xatolik yuz berdi.": { ru: "Произошла ошибка при сохранении отзыва.", en: "An error occurred while saving the review." },
  "Sharhni yuborish": { ru: "Отправить отзыв", en: "Submit review" },
  "Shaxsiy ma’lumotlar": { ru: "Личные данные", en: "Personal data" },
  "Shaxsni tasdiqlash arizalarini ko‘rib chiqing va ishonch belgisini boshqaring.": { ru: "Просматривайте заявки на подтверждение личности и управляйте значком доверия.", en: "Review identity verification applications and manage the trust badge." },
  "Shaxsni tasdiqlovchi hujjat": { ru: "Документ, удостоверяющий личность", en: "Identity document" },
  "Shikoyatlar yuklanmoqda...": { ru: "Загрузка жалоб...", en: "Loading complaints..." },
  "Shubhali holatlar bo‘lsa, savdo to‘xtatiladi.": { ru: "При подозрительных обстоятельствах сделка будет остановлена.", en: "In suspicious cases, the trade will be suspended." },
  "Sifat yoki qoidalarga mos emas": { ru: "Не соответствует качеству или правилам", en: "Does not meet quality or rules" },
  "Sotilgan akkauntni qaytarib olishga urinish doimiy blokga olib keladi.": { ru: "Попытка вернуть проданный аккаунт приведет к постоянной блокировке.", en: "Attempting to reclaim a sold account will result in a permanent ban." },
  "Sotish, buyurtmalar va profil bo‘limlari Telegram Mini App ichida ishlaydi.": { ru: "Разделы «Продажи», «Заказы» и «Профиль» работают внутри Telegram Mini App.", en: "Sell, orders, and profile sections work within the Telegram Mini App." },
  "Sotuv narxi": { ru: "Цена продажи", en: "Selling price" },
  "Sotuvchi akkaunt ma'lumotlarini tayyorlayapti.": { ru: "Продавец готовит данные аккаунта.", en: "Seller is preparing account details." },
  "Sotuvchi arizasi bo‘yicha qaror saqlandi": { ru: "Решение по заявке продавца сохранено", en: "Decision on seller's application saved" },
  "Sotuvchi batafsil tavsif qoldirmagan.": { ru: "Продавец не оставил подробного описания.", en: "Seller did not leave a detailed description." },
  "Sotuvchi bilan": { ru: "С продавцом", en: "With seller" },
  "Sotuvchi bilan yozishish uchun tizimga kiring.": { ru: "Для переписки с продавцом войдите в систему.", en: "Log in to chat with the seller." },
  "Sotuvchi markazi": { ru: "Центр продавца", en: "Seller Center" },
  "Sotuvchi payout": { ru: "Выплата продавцу", en: "Seller payout" },
  "Sotuvchi profili": { ru: "Профиль продавца", en: "Seller profile" },
  "Sotuvchi reytinglari": { ru: "Рейтинг продавца", en: "Seller ratings" },
  "Sotuvchi statusi": { ru: "Статус продавца", en: "Seller status" },
  "Sotuvchi tavsifi kiritilmagan.": { ru: "Описание продавца не добавлено.", en: "Seller description not added." },
  "Sotuvchi to‘lovi": { ru: "Комиссия продавца", en: "Seller fee" },
  "Sotuvchi uchun": { ru: "Для продавца", en: "For seller" },
  "Sotuvchi va xaridorlar bilan yozishish uchun Telegram orqali kiring.": { ru: "Для переписки с продавцами и покупателями войдите через Telegram.", en: "Log in via Telegram to chat with sellers and buyers." },
  "Sotuvchi verifikatsiyasi": { ru: "Верификация продавца", en: "Seller verification" },
  "Sotuvchi video qo‘shsa, shu oynada ko‘rishingiz mumkin.": { ru: "Если продавец добавит видео, вы сможете увидеть его в этом окне.", en: "If the seller adds a video, you can see it in this window." },
  "Sotuvchiga baho berish": { ru: "Оценить продавца", en: "Rate seller" },
  "Sotuvchiga yozish": { ru: "Написать продавцу", en: "Message seller" },
  "Sotuvlaringiz, balansingiz, saqlangan akkauntlaringiz va media boshqaruvi shu profilga ulanadi.": { ru: "Ваши продажи, баланс, сохраненные аккаунты и управление медиа будут привязаны к этому профилю.", en: "Your sales, balance, saved accounts, and media management will be linked to this profile." },
  "Soxta e’lon va o‘g‘irlangan akkaunt sotish.": { ru: "Фейковые объявления и продажа угнанных аккаунтов.", en: "Fake listings and selling stolen accounts." },
  "So‘rov yuborish": { ru: "Отправить запрос", en: "Send request" },
  "Spam yoki haqoratli kontent": { ru: "Спам или оскорбительный контент", en: "Spam or abusive content" },
  "Spam yoki haqoratli sharhlarni yashiring, asossiz shikoyatlarni yoping.": { ru: "Скрывайте спам или оскорбительные комментарии, закрывайте необоснованные жалобы.", en: "Hide spam or offensive comments, close unfounded complaints." },
  "Summani tanlang, kartaga o‘tkazing va chek rasmini yuboring. Balans admin tasdig‘idan keyin qo‘shiladi.": { ru: "Выберите сумму, переведите на карту и отправьте фото чека. Баланс будет добавлен после подтверждения администратором.", en: "Select the amount, transfer to the card, and send a photo of the receipt. The balance will be added after admin confirmation." },
  "Taklif qilingan foydalanuvchilar va haqiqiy yakunlangan savdolardan kelgan bonuslar referral ledger’da ko‘rsatiladi.": { ru: "Бонусы от приглашенных пользователей и фактически завершенных сделок отображаются в реферальном реестре.", en: "Bonuses from invited users and actually completed trades are shown in the referral ledger." },
  "Tanlangan akkaunt": { ru: "Выбранный аккаунт", en: "Selected account" },
  "Tanlangan akkauntlar": { ru: "Выбранные аккаунты", en: "Selected accounts" },
  "Tarmoq xatosi": { ru: "Ошибка сети", en: "Network error" },
  "Tasdiqlangan sotuvchi": { ru: "Подтвержденный продавец", en: "Verified seller" },
  "Tavsif yo‘q": { ru: "Нет описания", en: "No description" },
  "Tekshiruv qarori saqlandi": { ru: "Решение по проверке сохранено", en: "Review decision saved" },
  "Telegram orqali kirish kerak": { ru: "Необходимо войти через Telegram", en: "Must log in via Telegram" },
  "Telegram profili ulandi": { ru: "Профиль Telegram подключен", en: "Telegram profile connected" },
  "Telegram sessiyasi topilmadi. Pastdagi telefon raqam orqali kirishdan foydalaning.": { ru: "Сессия Telegram не найдена. Воспользуйтесь входом по номеру телефона ниже.", en: "Telegram session not found. Use phone number login below." },
  "Telegram’da ulashish": { ru: "Поделиться в Telegram", en: "Share on Telegram" },
  "Tez-tez so‘raladigan savollar va shaxsiy murojaatlaringiz shu yerda.": { ru: "Часто задаваемые вопросы и ваши личные обращения здесь.", en: "FAQs and your personal requests are here." },
  "To'lov muzlatildi, sotuvchi javobini kutmoqdamiz.": { ru: "Платеж заморожен, ждем ответа продавца.", en: "Payment frozen, waiting for seller's reply." },
  "To‘g‘ri summa kiriting": { ru: "Введите корректную сумму", en: "Enter correct amount" },
  "To‘g‘ridan-to‘g‘ri admin bilan bog‘laning.": { ru: "Свяжитесь напрямую с админом.", en: "Contact admin directly." },
  "To‘liq ism": { ru: "Полное имя", en: "Full name" },
  "To‘lov chekini rasm qilib yuklang": { ru: "Загрузите чек об оплате как фото", en: "Upload payment receipt as image" },
  "To‘lov muzlatildi": { ru: "Платеж заморожен", en: "Payment frozen" },
  "To‘lov va balans": { ru: "Оплата и баланс", en: "Payment and balance" },
  "To‘lov va escrow tayyorgarligi": { ru: "Оплата и подготовка эскроу", en: "Payment and escrow preparation" },
  "Tranzaksiyalarni ko‘rish uchun Telegram orqali kiring": { ru: "Войдите через Telegram для просмотра транзакций", en: "Log in via Telegram to view transactions" },
  "Trust profile": { ru: "Профиль доверия", en: "Trust profile" },
  "Uploadlarni tasdiqlang, kategoriya va FAQ’ni boshqaring, murojaatlarga javob bering.": { ru: "Подтверждайте загрузки, управляйте категориями и FAQ, отвечайте на обращения.", en: "Approve uploads, manage categories & FAQs, respond to requests." },
  "Verifikatsiyalangan sotuvchi": { ru: "Верифицированный продавец", en: "Verified seller" },
  "Video 200 MB dan kichik bo‘lishi kerak.": { ru: "Видео должно быть меньше 200 МБ.", en: "Video must be smaller than 200 MB." },
  "Video bo‘lsa, afzallik beradi": { ru: "Наличие видео дает преимущество", en: "Video is preferred" },
  "Video hali yuklanmagan": { ru: "Видео еще не загружено", en: "Video not uploaded yet" },
  "Video yuklanmoqda": { ru: "Видео загружается", en: "Video is uploading" },
  "Video yuklashda tarmoq xatosi": { ru: "Ошибка сети при загрузке видео", en: "Network error uploading video" },
  "Videoni yuklash": { ru: "Загрузить видео", en: "Upload video" },
  "Xabar yuborilmadi": { ru: "Сообщение не отправлено", en: "Message not sent" },
  "Xabar yuborish": { ru: "Отправить сообщение", en: "Send message" },
  "Xabarlar yuklanmoqda...": { ru: "Сообщения загружаются...", en: "Messages are loading..." },
  "Xaridni tasdiqlash": { ru: "Подтвердить покупку", en: "Confirm purchase" },
  "Xaridor bahosi": { ru: "Оценка покупателя", en: "Buyer rating" },
  "Xaridor bilan": { ru: "С покупателем", en: "With buyer" },
  "Xaridor izoh qoldirmagan.": { ru: "Покупатель не оставил отзыв.", en: "Buyer left no comment." },
  "Xaridor tasdig‘i": { ru: "Подтверждение покупателя", en: "Buyer's confirmation" },
  "Xaridor tasdig‘iga o‘tish": { ru: "Перейти к подтверждению покупателя", en: "Go to buyer confirmation" },
  "Xaridor tasdiqlagach mablag‘ sotuvchiga beriladi.": { ru: "После подтверждения покупателем средства будут переданы продавцу.", en: "Funds will be released to seller after buyer's confirmation." },
  "Xaridor tasdiqlanmoqda": { ru: "Покупатель подтверждается", en: "Buyer is confirming" },
  "Xaridor uchun": { ru: "Для покупателя", en: "For buyer" },
  "Xaridorlar fikri": { ru: "Отзывы покупателей", en: "Buyer feedback" },
  "Xato yuz berdi": { ru: "Произошла ошибка", en: "An error occurred" },
  "Xavfsiz PUBG akkaunt savdo platformasi": { ru: "Безопасная платформа для продажи аккаунтов PUBG", en: "Secure PUBG account trading platform" },
  "Yakunlangan savdodan keyin sotuvchiga xolis baho qoldiring. Sharhlar faqat real buyurtma orqali yuboriladi.": { ru: "Оставьте честную оценку продавцу после завершенной сделки. Отзывы отправляются только через реальный заказ.", en: "Leave an honest rating for the seller after a completed trade. Reviews are only submitted through a real order." },
  "Yangi admin qarorlari shu yerda ko‘rinadi.": { ru: "Новые решения администратора будут видны здесь.", en: "New admin decisions will appear here." },
  "Yangi alertlar": { ru: "Новые оповещения", en: "New alerts" },
  "Yangi e’lon": { ru: "Новое объявление", en: "New listing" },
  "Yangi e’lon kelganda shu yerda ko‘rinadi.": { ru: "Новое объявление появится здесь.", en: "New listing will appear here." },
  "Yangi kategoriya": { ru: "Новая категория", en: "New Category" },
  "Yangi murojaatlar shu yerda ko‘rinadi.": { ru: "Новые обращения отображаются здесь.", en: "New inquiries will appear here." },
  "Yangi savol yuborish": { ru: "Задать новый вопрос", en: "Send New Question" },
  "Yangi sotuvchi": { ru: "Новый продавец", en: "New Seller" },
  "Yangi sotuvchi arizasi yuborilganda shu yerda ko‘rinadi.": { ru: "Когда будет отправлена новая заявка продавца, она появится здесь.", en: "New seller applications will appear here when submitted." },
  "Yechib olish so‘rovi": { ru: "Запрос на вывод", en: "Withdrawal Request" },
  "Yechib olish so‘rovi qabul qilindi": { ru: "Запрос на вывод принят", en: "Withdrawal Request Accepted" },
  "Yuborishda xatolik": { ru: "Ошибка отправки", en: "Submission Error" },
  "lmadi, original yuboriladi:": { ru: "не удалось, отправлен оригинал:", en: "failed, original sent:" },
  "proq yuklash": { ru: "загрузить приложение", en: "download app" },
  "xavfsiz bozor.": { ru: "безопасный рынок.", en: "secure marketplace." },
  "Ko‘proq": { ru: "Подробнее", en: "More" },
  "Yopish": { ru: "Закрыть", en: "Close" },
  "Yechish": { ru: "Вывод", en: "Withdraw" },
  "To‘ldirish": { ru: "Пополнить", en: "Top up" },
  "Profil rasmi": { ru: "Фото профиля", en: "Profile photo" },
  "Kadrni sozlang — faqat doira ichidagi qism saqlanadi.": { ru: "Настройте кадр — сохранится только часть внутри круга.", en: "Adjust the frame — only the part inside the circle is saved." },
  "Kattalashtirish": { ru: "Масштаб", en: "Zoom" },
  "Gorizontal": { ru: "По горизонтали", en: "Horizontal" },
  "Vertikal": { ru: "По вертикали", en: "Vertical" },
  "Saqlash": { ru: "Сохранить", en: "Save" },
  "Saqlanmoqda...": { ru: "Сохранение...", en: "Saving..." },
  "Profil rasmi yangilandi": { ru: "Фото профиля обновлено", en: "Profile photo updated" },
  "✅ Balansga tushdi": { ru: "✅ Зачислено на баланс", en: "✅ Credited to balance" },
  "❌ Tushmadi": { ru: "❌ Не зачислено", en: "❌ Not credited" },
  "⏳ Tekshirilmoqda": { ru: "⏳ На проверке", en: "⏳ Under review" },
  "✅ Bozorda": { ru: "✅ На маркете", en: "✅ Live" },
  "❌ Rad etilgan": { ru: "❌ Отклонено", en: "❌ Rejected" },
  "⏳ Admin tekshiruvida": { ru: "⏳ На проверке админа", en: "⏳ Awaiting admin review" },
  "E’lon avval admin tekshiruvidan o‘tadi, tasdiqlangach bozorda ko‘rinadi. Rad etilsa sababi shu yerda ko‘rsatiladi.": { ru: "Объявление сначала проходит проверку админа и появляется на маркете после одобрения. При отказе причина будет показана здесь.", en: "The listing is reviewed by an admin first and appears on the market after approval. If rejected, the reason is shown here." },
  "E’lon admin tekshiruviga yuborildi. Tasdiqlangach bozorda ko‘rinadi.": { ru: "Объявление отправлено на проверку админа. После одобрения появится на маркете.", en: "Listing sent for admin review. It will appear on the market once approved." },
  "Tasdiqlash/rad etish sababi (foydalanuvchiga ko‘rinadi)": { ru: "Причина одобрения/отказа (видна пользователю)", en: "Approval/rejection reason (visible to the user)" },
  "E’lon tekshiruvga yuborildi": { ru: "Объявление отправлено на проверку", en: "Listing sent for review" },
  "E’lon tasdiqlandi": { ru: "Объявление одобрено", en: "Listing approved" },
  "E’lon rad etildi": { ru: "Объявление отклонено", en: "Listing rejected" },
  "Rasm manzili noto‘g‘ri": { ru: "Неверный адрес изображения", en: "Invalid image address" },
  "3 ta ustunli ko'rinish": { ru: "Вид в 3 колонки", en: "3-column view" },
  "5 qatorli ixcham ko'rinish": { ru: "Компактный вид, 5 строк", en: "Compact 5-row view" },
  "Admin kirishi kerak": { ru: "Требуется вход администратора", en: "Admin login required" },
  "Admin ko'rigidan o'tadi": { ru: "Проходит проверку админа", en: "Goes through admin review" },
  "Akkaunt ma’lumotlari (ID, level, K/D, skinlar) haqiqiy bo‘lishi shart.": { ru: "Данные аккаунта (ID, уровень, K/D, скины) должны быть настоящими.", en: "Account data (ID, level, K/D, skins) must be genuine." },
  "Akkaunt qanday tekshiriladi?": { ru: "Как проверяется аккаунт?", en: "How is an account verified?" },
  "Akkauntlarni to'liq ma'lumot, rasm va video bilan solishtiring. Kafolatli savdo jarayoni orqali ishonch bilan xarid qiling yoki o'z e'loningizni joylang.": { ru: "Сравнивайте аккаунты по полной информации, фото и видео. Покупайте уверенно через гарантированную сделку или разместите своё объявление.", en: "Compare accounts with full details, photos and videos. Buy confidently through escrow or post your own listing." },
  "Avval summani tanlang": { ru: "Сначала выберите сумму", en: "Select an amount first" },
  "Avval yakunlangan buyurtmani tanlang.": { ru: "Сначала выберите завершённый заказ.", en: "Select a completed order first." },
  "A’zo bo‘lgan": { ru: "Дата регистрации", en: "Member since" },
  "Balans": { ru: "Баланс", en: "Balance" },
  "Barcha bildirishnomalar": { ru: "Все уведомления", en: "All notifications" },
  "Barcha mintaqalar": { ru: "Все регионы", en: "All regions" },
  "Barcha savdolar faqat platforma escrow tizimi orqali amalga oshiriladi.": { ru: "Все сделки проходят только через escrow-систему платформы.", en: "All trades go only through the platform escrow system." },
  "Barcha toifalar": { ru: "Все категории", en: "All categories" },
  "Barcha tranzaksiyalar": { ru: "Все транзакции", en: "All transactions" },
  "Bildirishnomalar va kuzatuv": { ru: "Уведомления и отслеживание", en: "Notifications & tracking" },
  "Bozor ko‘rsatkichlari": { ru: "Показатели маркета", en: "Market metrics" },
  "Bo‘sh": { ru: "Пусто", en: "Empty" },
  "Bu bo'limda xavfsiz savdo jarayoni va admin ko'rigi orqali barcha tomonlar uchun aniq tartib saqlanadi. Shaxsiy ma'lumotlarni ochiq e'lon maydoniga yozmang.": { ru: "В этом разделе безопасная сделка и проверка админом обеспечивают понятный порядок для всех сторон. Не публикуйте личные данные в открытом объявлении.", en: "This section keeps a clear process for all sides via escrow and admin review. Never put personal data in a public listing." },
  "Buyurtma va e’lonlar": { ru: "Заказы и объявления", en: "Orders & listings" },
  "Buyurtmani tanlang": { ru: "Выберите заказ", en: "Select an order" },
  "Cheklar yo‘q": { ru: "Чеков нет", en: "No receipts" },
  "Daraja bo‘yicha": { ru: "По уровню", en: "By level" },
  "E'lon ma'lumotlarini aniq va to'liq kiriting.": { ru: "Заполните данные объявления точно и полностью.", en: "Enter listing details accurately and completely." },
  "Eng yangi": { ru: "Самые новые", en: "Newest" },
  "Escrow, chat, nizo va referral holatlari haqida xabarlar.": { ru: "Уведомления о сделках, чате, спорах и рефералах.", en: "Updates about escrow, chat, disputes and referrals." },
  "E’lon o‘chirildi.": { ru: "Объявление удалено.", en: "Listing deleted." },
  "E’lonni o‘chirib bo‘lmadi.": { ru: "Не удалось удалить объявление.", en: "Could not delete the listing." },
  "E’lonni o‘chirish": { ru: "Удалить объявление", en: "Delete listing" },
  "Gamer, neon yoki klassik dark temani tanlang — tanlov profilga saqlanadi.": { ru: "Выберите тему Gamer, Neon или классическую тёмную — выбор сохранится в профиле.", en: "Pick the Gamer, Neon or classic dark theme — the choice is saved to your profile." },
  "Hali yakunlangan savdo yo‘q": { ru: "Завершённых сделок пока нет", en: "No completed trades yet" },
  "Hali yakunlangan savdo yo‘q.": { ru: "Завершённых сделок пока нет.", en: "No completed trades yet." },
  "Hozircha chat yo‘q. Akkaunt sahifasidan “Sotuvchiga yozish”ni bosing.": { ru: "Чатов пока нет. Нажмите «Написать продавцу» на странице аккаунта.", en: "No chats yet. Tap “Message seller” on an account page." },
  "Ibora yoki tarjimani qidirish...": { ru: "Поиск фразы или перевода...", en: "Search phrase or translation..." },
  "Ichki wallet orqali escrow to‘lovi hozir ishlaydi. Click va Payme merchant konfiguratsiyasi qo‘shilgach tashqi checkout ham yoqiladi.": { ru: "Оплата через escrow с внутреннего кошелька работает уже сейчас. Внешняя оплата включится после настройки мерчантов Click и Payme.", en: "Escrow payment from the internal wallet works now. External checkout turns on once Click and Payme merchants are configured." },
  "Inferno Stealth xavfsizligi, tekshiruv va savdo nazorati.": { ru: "Безопасность, проверка и контроль сделок Inferno Stealth.", en: "Inferno Stealth security, verification and trade control." },
  "Inferno Stealth'dan xavfsiz foydalanish bo'yicha asosiy javoblar.": { ru: "Основные ответы о безопасном использовании Inferno Stealth.", en: "Key answers about using Inferno Stealth safely." },
  "Inventar va skinlar": { ru: "Инвентарь и скины", en: "Inventory & skins" },
  "Ishonchli sotuvchi": { ru: "Надёжный продавец", en: "Trusted seller" },
  "JPG, PNG yoki WEBP · maksimum 8 MB": { ru: "JPG, PNG или WEBP · максимум 8 МБ", en: "JPG, PNG or WEBP · max 8 MB" },
  "Jami o‘yin": { ru: "Всего игр", en: "Total matches" },
  "Kafolatli savdoda pul xaridor tasdig‘igacha muzlatilgan holatda turadi. Login yoki parolni platformadan tashqari kanallarda yubormang.": { ru: "При гарантированной сделке деньги заморожены до подтверждения покупателя. Не отправляйте логин и пароль вне платформы.", en: "In escrow the money stays frozen until the buyer confirms. Never send login or password outside the platform." },
  "Kirishdan so'ng buyurtma berish mumkin.": { ru: "Заказ можно оформить после входа.", en: "You can order after logging in." },
  "Ko'p beriladigan savollar": { ru: "Часто задаваемые вопросы", en: "Frequently asked questions" },
  "Ko'proq": { ru: "Больше", en: "More" },
  "Ko‘rinish (tema)": { ru: "Оформление (тема)", en: "Appearance (theme)" },
  "Ko‘rish": { ru: "Просмотр", en: "View" },
  "Ko‘rishlar": { ru: "Просмотры", en: "Views" },
  "Kuzatuv o‘chirildi": { ru: "Отслеживание отключено", en: "Tracking disabled" },
  "Legend sotuvchi": { ru: "Легендарный продавец", en: "Legend seller" },
  "Matnni tahrirlab saqlaganda o‘zgarish barcha foydalanuvchilarda real vaqtda ko‘rinadi.": { ru: "После сохранения правки текста изменения видны всем пользователям в реальном времени.", en: "Once you save an edited text, the change appears for all users in real time." },
  "Media S3 xotirasiga saqlandi va akkaunt ma’lumotlari ommaviy bozorga chiqarildi. Profil bo‘limidan narx, tavsif va asosiy ma’lumotlarni tahrirlashingiz mumkin.": { ru: "Медиа сохранены в хранилище S3, аккаунт опубликован на маркете. Цену, описание и основные данные можно изменить в профиле.", en: "Media is stored in S3 and the account is published to the market. You can edit price, description and key details in your profile." },
  "Mintaqani kiriting.": { ru: "Укажите регион.", en: "Enter the region." },
  "Mintaqani tanlang.": { ru: "Выберите регион.", en: "Select a region." },
  "Narx": { ru: "Цена", en: "Price" },
  "Narx kuzatuvi": { ru: "Отслеживание цены", en: "Price tracking" },
  "Narx kuzatuvi yoqildi": { ru: "Отслеживание цены включено", en: "Price tracking enabled" },
  "Narx oralig'i": { ru: "Диапазон цен", en: "Price range" },
  "Narx tushdi": { ru: "Цена снизилась", en: "Price dropped" },
  "Narx tushishi ogohlantirishi": { ru: "Оповещение о снижении цены", en: "Price drop alert" },
  "Narx: arzondan": { ru: "Цена: сначала дешевле", en: "Price: low to high" },
  "Narx: qimmatdan": { ru: "Цена: сначала дороже", en: "Price: high to low" },
  "Nizo va yordam": { ru: "Споры и поддержка", en: "Disputes & support" },
  "Qidiruv bo‘yicha ibora topilmadi.": { ru: "По запросу фраза не найдена.", en: "No phrase found for this search." },
  "Qo‘llab-quvvatlash": { ru: "Поддержка", en: "Support" },
  "Qo‘shish": { ru: "Добавить", en: "Add" },
  "Rasm va video 200 MB gacha (JPG, PNG, WEBP, MP4, MOV, WEBM)": { ru: "Фото и видео до 200 МБ (JPG, PNG, WEBP, MP4, MOV, WEBM)", en: "Photos and videos up to 200 MB (JPG, PNG, WEBP, MP4, MOV, WEBM)" },
  "Rasm va videolarni tanlang": { ru: "Выберите фото и видео", en: "Select photos and videos" },
  "Reytinglar va sharhlar": { ru: "Рейтинги и отзывы", en: "Ratings & reviews" },
  "Sabab va batafsil izohni kiriting": { ru: "Укажите причину и подробное описание", en: "Enter the reason and a detailed note" },
  "Saqlab bo‘lmadi": { ru: "Не удалось сохранить", en: "Could not save" },
  "Savdolaringiz holati va kafolat bosqichlarini shu yerdan kuzating.": { ru: "Следите за статусом сделок и этапами гарантии здесь.", en: "Track your trade status and escrow stages here." },
  "Sizning e’lonlaringiz bo‘yicha hali sharhlar mavjud emas. Birinchi savdolardan keyin bu yerda haqiqiy xaridor fikrlari ko‘rinadi.": { ru: "По вашим объявлениям пока нет отзывов. После первых сделок здесь появятся реальные мнения покупателей.", en: "No reviews on your listings yet. Real buyer feedback will appear here after your first trades." },
  "Tanlangan e'lon": { ru: "Выбранное объявление", en: "Selected listing" },
  "Tanlangan holat bo‘yicha manual top-up topilmadi.": { ru: "По выбранному статусу пополнений не найдено.", en: "No manual top-ups found for the selected status." },
  "Tarjima saqlandi va real vaqtda qo‘llandi": { ru: "Перевод сохранён и применён в реальном времени", en: "Translation saved and applied in real time" },
  "Tekshirilishi kerak": { ru: "Требует проверки", en: "Needs review" },
  "Telegram push va narx tushishi haqidagi ogohlantirishlar.": { ru: "Push-уведомления в Telegram и оповещения о снижении цены.", en: "Telegram push and price-drop alerts." },
  "Tema profilga saqlandi": { ru: "Тема сохранена в профиль", en: "Theme saved to profile" },
  "Temani saqlab bo‘lmadi": { ru: "Не удалось сохранить тему", en: "Could not save the theme" },
  "Tiklab bo‘lmadi": { ru: "Не удалось восстановить", en: "Could not restore" },
  "To'lov kafolatda": { ru: "Оплата под гарантией", en: "Payment in escrow" },
  "To‘landi": { ru: "Оплачено", en: "Paid" },
  "To‘lov qachon sotuvchiga beriladi?": { ru: "Когда оплата поступает продавцу?", en: "When does the seller get paid?" },
  "To‘lovlar": { ru: "Платежи", en: "Payments" },
  "Videoni ko‘rish": { ru: "Смотреть видео", en: "Watch video" },
  "Xavfsiz PUBG akkaunt bozori": { ru: "Безопасный маркет PUBG аккаунтов", en: "Secure PUBG account marketplace" },
  "Yakunlangan buyurtmalar bo‘yicha kunlik tushum": { ru: "Ежедневная выручка по завершённым заказам", en: "Daily revenue from completed orders" },
  "Yakunlangan savdolar daromadi bo‘yicha": { ru: "По доходу от завершённых сделок", en: "By completed trade revenue" },
  "Yakunlangan savdolar va reyting bo‘yicha": { ru: "По завершённым сделкам и рейтингу", en: "By completed trades and rating" },
  "Yana e'lon berish": { ru: "Разместить ещё объявление", en: "Post another listing" },
  "Yangi": { ru: "Новое", en: "New" },
  "Yangi FAQ": { ru: "Новый FAQ", en: "New FAQ" },
  "Yangi foydalanuvchi": { ru: "Новый пользователь", en: "New user" },
  "Yangi user": { ru: "Новый пользователь", en: "New user" },
  "Yaxshi e'lon formulasi": { ru: "Формула хорошего объявления", en: "Good listing formula" },
  "Yordam va Qoidalar": { ru: "Помощь и правила", en: "Help & Rules" },
  "Yordam va qoidalar": { ru: "Помощь и правила", en: "Help & rules" },
  "so'm": { ru: "сум", en: "UZS" },
  "so‘m": { ru: "сум", en: "UZS" },
  "To'lov": { ru: "Оплата", en: "Payment" },
  "Hammasini ko'rish": { ru: "Смотреть все", en: "View all" },
  "Grid ko'rinishi": { ru: "Вид сеткой", en: "Grid view" },
  "Ko'proq yuklash": { ru: "Загрузить ещё", en: "Load more" },
  "Ko'rish": { ru: "Просмотр", en: "View" },
  "Ko‘pi bilan": { ru: "Максимум", en: "At most" },
  "Jami o'yin": { ru: "Всего игр", en: "Total matches" },
  "Jami o'yinlar": { ru: "Всего игр", en: "Total matches" },
  "Akkaunt ochilgan yil": { ru: "Год создания аккаунта", en: "Account creation year" },
  "Kuzatuvni o‘chirish": { ru: "Отключить отслеживание", en: "Disable tracking" },
  "Ma’lumot yuklanmoqda yoki e’lon o‘chirilgan.": { ru: "Данные загружаются или объявление удалено.", en: "Data is loading or the listing was deleted." },
  "Minimum 10 000 so‘m; so‘rov admin tomonidan ko‘rib chiqiladi": { ru: "Минимум 10 000 сум; заявку рассмотрит админ", en: "Minimum 10,000 UZS; the request is reviewed by an admin" },
  "Muammo yuz bergan buyurtma raqamini kiriting. Login yoki parolni bu formaga yozmang; dalil sifatida faqat xavfsiz media havolalaridan foydalaning.": { ru: "Укажите номер проблемного заказа. Не пишите логин или пароль в этой форме; в качестве доказательства используйте только безопасные ссылки на медиа.", en: "Enter the number of the problematic order. Do not write login or password here; use only safe media links as evidence." },
  "📸 To‘lov chekini tanlang": { ru: "📸 Выберите чек об оплате", en: "📸 Select the payment receipt" },
  "Filtrlar": { ru: "Фильтры", en: "Filters" },
  "Asosiy": { ru: "Главная", en: "Home" },
  "Bozor": { ru: "Маркет", en: "Market" },
  "Sotish": { ru: "Продать", en: "Sell" },
  "Buyurtma": { ru: "Заказы", en: "Orders" },
  "Buyurtmalar": { ru: "Заказы", en: "Orders" },
  "Profil": { ru: "Профиль", en: "Profile" },
  "Saqlanganlar": { ru: "Избранное", en: "Saved" },
  "Tranzaksiya": { ru: "Транзакции", en: "Transactions" },
  "Tranzaksiyalar": { ru: "Транзакции", en: "Transactions" },
  "Qoidalar": { ru: "Правила", en: "Rules" },
  "Referal": { ru: "Рефералы", en: "Referral" },
  "Yordam": { ru: "Поддержка", en: "Support" },
  "Til": { ru: "Язык", en: "Language" },
  "Tahrirlash": { ru: "Изменить", en: "Edit" },
  "O‘chirish": { ru: "Удалить", en: "Delete" },
  "O'chirish": { ru: "Удалить", en: "Delete" },
  "Jarayon": { ru: "Процесс", en: "Process" },
  "Batafsil tavsif": { ru: "Подробное описание", en: "Detailed description" },
  "Daraja": { ru: "Уровень", en: "Level" },
  "Mintaqa": { ru: "Регион", en: "Region" },
  "O'yinchi nomi": { ru: "Имя игрока", en: "Player name" },
  "K/D nisbati": { ru: "K/D соотношение", en: "K/D ratio" },
  "G'alaba foizi": { ru: "Процент побед", en: "Win rate" },
  "Headshot foizi": { ru: "Процент хедшотов", en: "Headshot rate" },
  "UC balansi": { ru: "Баланс UC", en: "UC balance" },
  "Kiyimlar soni": { ru: "Количество нарядов", en: "Outfit count" },
  "Qurol skinlari": { ru: "Скины оружия", en: "Gun skins" },
  "Transport soni": { ru: "Количество транспорта", en: "Vehicle count" },
  "Narxi (so'm)": { ru: "Цена (сум)", en: "Price (UZS)" },
  "Asosiy skinlar": { ru: "Основные скины", en: "Key skins" },
  "Conqueror tarixi bor": { ru: "Есть история Conqueror", en: "Has Conqueror history" },
  "X-Suit mavjud": { ru: "Есть X-Suit", en: "Has X-Suit" },
  "Kafolatli savdo": { ru: "Гарантированная сделка", en: "Escrow trade" },
  "Rasm + video": { ru: "Фото + видео", en: "Photo + video" },
  "Admin nazorati": { ru: "Контроль админа", en: "Admin control" },
  "Barchasi": { ru: "Все", en: "All" },
  "Yechib olish": { ru: "Вывести", en: "Withdraw" },
  "Sotib olish": { ru: "Купить", en: "Buy" },
  "Kutilmoqda": { ru: "В ожидании", en: "Pending" },
  "Tasdiqlangan": { ru: "Подтверждено", en: "Approved" },
  "Rad etilgan": { ru: "Отклонено", en: "Rejected" },
  "Tasdiqlash": { ru: "Подтвердить", en: "Approve" },
  "Rad etish": { ru: "Отклонить", en: "Reject" },
  "Xavfsiz chat": { ru: "Безопасный чат", en: "Secure chat" },
  "Inferno xavfsiz chat": { ru: "Безопасный чат Inferno", en: "Inferno secure chat" },
  "Yuborilmoqda...": { ru: "Отправляется...", en: "Sending..." },
  "Savdo tafsiloti": { ru: "Детали сделки", en: "Trade details" },
  "Hisobot": { ru: "Отчет", en: "Report" },
  "Admin tekshiruvi kutilmoqda": { ru: "Ожидается проверка админа", en: "Awaiting admin review" },
  "Admin markazi": { ru: "Центр админа", en: "Admin center" },
  "Xavfsizlik": { ru: "Безопасность", en: "Security" },
  "Admin panel": { ru: "Панель админа", en: "Admin panel" },
  "Admin paneli": { ru: "Панель админа", en: "Admin panel" },
  "O‘qildi": { ru: "Прочитано", en: "Read" },
  "Belgilangan narxga tushganda darhol xabar olasiz.": { ru: "Вы сразу получите уведомление, когда цена опустится до указанной.", en: "You get notified instantly when the price drops to your target." },
  "Xavfsiz savdo markazi": { ru: "Центр безопасной торговли", en: "Secure trading hub" },
  "Savdo voronkasi": { ru: "Воронка продаж", en: "Sales funnel" },
  "100% Tekshirilgan": { ru: "100% проверено", en: "100% verified" },
  "20+ savdo, 4.5+ reyting": { ru: "20+ сделок, рейтинг 4.5+", en: "20+ trades, 4.5+ rating" },
  "5+ yakunlangan savdo": { ru: "5+ завершённых сделок", en: "5+ completed trades" },
  "50+ savdo, 4.7+ reyting": { ru: "50+ сделок, рейтинг 4.7+", en: "50+ trades, 4.7+ rating" },
  "Akkauntlar": { ru: "Аккаунты", en: "Accounts" },
  "Analitika yuklanmoqda...": { ru: "Загрузка аналитики...", en: "Loading analytics..." },
  "BOOTING SYSTEM": { ru: "ЗАПУСК СИСТЕМЫ", en: "BOOTING SYSTEM" },
  "Bahsli vaziyatlar": { ru: "Спорные ситуации", en: "Disputes" },
  "Bildirishnoma sozlamalari": { ru: "Настройки уведомлений", en: "Notification settings" },
  "Bildirishnomalar": { ru: "Уведомления", en: "Notifications" },
  "Bitimni platformadan tashqarida yakunlamang.": { ru: "Не завершайте сделку вне платформы.", en: "Do not complete the deal outside the platform." },
  "Bosh atishlar": { ru: "Хедшоты", en: "Headshots" },
  "Bosh atishlar foizi": { ru: "Процент хедшотов", en: "Headshot rate" },
  "Buyurtma berilmoqda...": { ru: "Оформление заказа...", en: "Placing order..." },
  "Buyurtma holatlari": { ru: "Статусы заказов", en: "Order statuses" },
  "Buyurtma yaratildi. Kafolatli savdo bosqichi boshlandi.": { ru: "Заказ создан. Начался этап безопасной сделки.", en: "Order created. Escrow stage has started." },
  "Buyurtmalarga qaytish": { ru: "Назад к заказам", en: "Back to orders" },
  "Chatlar": { ru: "Чаты", en: "Chats" },
  "Chek hajmi 8 MB dan oshmasin": { ru: "Размер чека не должен превышать 8 МБ", en: "Receipt must be under 8 MB" },
  "Eng faol sotuvchilar": { ru: "Самые активные продавцы", en: "Top active sellers" },
  "E’lonlar": { ru: "Объявления", en: "Listings" },
  "Faol": { ru: "Активен", en: "Active" },
  "Faol bonuslar": { ru: "Активные бонусы", en: "Active bonuses" },
  "Faol buyurtma": { ru: "Активный заказ", en: "Active order" },
  "Faol buyurtmalar": { ru: "Активные заказы", en: "Active orders" },
  "Faol e’lonlar": { ru: "Активные объявления", en: "Active listings" },
  "Foydalanuvchilar": { ru: "Пользователи", en: "Users" },
  "Holat": { ru: "Статус", en: "Status" },
  "Izohsiz sharh": { ru: "Отзыв без комментария", en: "Review without comment" },
  "Jami bonus": { ru: "Всего бонусов", en: "Total bonus" },
  "Jami daromad": { ru: "Общий доход", en: "Total revenue" },
  "Jami foydalanuvchilar": { ru: "Всего пользователей", en: "Total users" },
  "Jami savdo": { ru: "Всего сделок", en: "Total trades" },
  "Jami tushum:": { ru: "Итого поступлений:", en: "Total income:" },
  "Javob yozing...": { ru: "Напишите ответ...", en: "Write a reply..." },
  "Kadrlash imkonsiz": { ru: "Кадрирование недоступно", en: "Cropping unavailable" },
  "Karta sozlanmagan": { ru: "Карта не настроена", en: "Card not configured" },
  "Kategoriyalar": { ru: "Категории", en: "Categories" },
  "Kiritilmagan": { ru: "Не указано", en: "Not provided" },
  "Kiyimlar": { ru: "Одежда", en: "Outfits" },
  "Mashinalar": { ru: "Машины", en: "Vehicles" },
  "Mashinalar soni": { ru: "Количество машин", en: "Vehicle count" },
  "Maslahatlar": { ru: "Советы", en: "Tips" },
  "Maxsus skinlar": { ru: "Особые скины", en: "Rare skins" },
  "Media fayllar qayerda saqlanadi?": { ru: "Где хранятся медиафайлы?", en: "Where are media files stored?" },
  "Media tayyorlanmoqda...": { ru: "Подготовка медиа...", en: "Preparing media..." },
  "Mening Buyurtmalarim": { ru: "Мои заказы", en: "My orders" },
  "Mening murojaatlarim": { ru: "Мои обращения", en: "My tickets" },
  "Muammoni batafsil yozing...": { ru: "Опишите проблему подробно...", en: "Describe the issue in detail..." },
  "Muvaffaqiyatli": { ru: "Успешно", en: "Successful" },
  "Muvaffaqiyatsiz": { ru: "Неуспешно", en: "Failed" },
  "Nizo ochish": { ru: "Открыть спор", en: "Open dispute" },
  "Nizolar": { ru: "Споры", en: "Disputes" },
  "Nusxa olingan": { ru: "Скопировано", en: "Copied" },
  "Ochiq nizolar": { ru: "Открытые споры", en: "Open disputes" },
  "Oxirgi moliyaviy harakatlar": { ru: "Последние финансовые операции", en: "Recent financial activity" },
  "PREVIEW TAYYORLANMOQDA": { ru: "ПРЕВЬЮ ГОТОВИТСЯ", en: "PREVIEW LOADING" },
  "Payout rad etildi.": { ru: "Выплата отклонена.", en: "Payout rejected." },
  "Pro filtrlari": { ru: "Pro-фильтры", en: "Pro filters" },
  "Pul bitim yakunigacha himoyalangan.": { ru: "Деньги защищены до завершения сделки.", en: "Funds are protected until the deal is complete." },
  "Qidirish": { ru: "Поиск", en: "Search" },
  "Qidirish...": { ru: "Поиск...", en: "Search..." },
  "Qidiruv filtrlari": { ru: "Фильтры поиска", en: "Search filters" },
  "Qurol skinlari soni": { ru: "Количество скинов оружия", en: "Weapon skin count" },
  "Rasm hajmi 8 MB dan oshmasin": { ru: "Размер изображения не должен превышать 8 МБ", en: "Image must be under 8 MB" },
  "Rasmni yuklashda xatolik": { ru: "Ошибка при загрузке изображения", en: "Image upload failed" },
  "Reyting": { ru: "Рейтинг", en: "Rating" },
  "Sana": { ru: "Дата", en: "Date" },
  "Savdo": { ru: "Сделки", en: "Trades" },
  "Savdo boshqaruvi": { ru: "Управление сделками", en: "Trade management" },
  "Savdo tajribangizni yozing...": { ru: "Опишите ваш опыт сделки...", en: "Describe your trading experience..." },
  "Savdo tarixi shakllanmoqda": { ru: "История сделок формируется", en: "Trade history is building up" },
  "Savdo yakunlandi": { ru: "Сделка завершена", en: "Trade completed" },
  "Savolingiz javobsiz qoldimi?": { ru: "Остался вопрос без ответа?", en: "Still have a question?" },
  "Sharh qoldiring": { ru: "Оставьте отзыв", en: "Leave a review" },
  "Sharh shikoyatlari": { ru: "Жалобы на отзывы", en: "Review reports" },
  "Sharhlar": { ru: "Отзывы", en: "Reviews" },
  "Sizga qoldirilgan sharhlar": { ru: "Отзывы о вас", en: "Reviews about you" },
  "Sizning referral kodingiz": { ru: "Ваш реферальный код", en: "Your referral code" },
  "Skin ma’lumoti kiritilmagan": { ru: "Информация о скинах не указана", en: "No skin info provided" },
  "Skinlar": { ru: "Скины", en: "Skins" },
  "Sotilgan": { ru: "Продано", en: "Sold" },
  "Sotuvchi": { ru: "Продавец", en: "Seller" },
  "Sotuvchi ishonchi": { ru: "Доверие к продавцу", en: "Seller trust" },
  "Sotuvchi ma’lumoti yuklanmoqda...": { ru: "Загрузка данных продавца...", en: "Loading seller info..." },
  "TEKSHIRILGAN": { ru: "ПРОВЕРЕНО", en: "VERIFIED" },
  "TIZIMGA KIRILMOQDA": { ru: "ВХОД В СИСТЕМУ", en: "LOGGING IN" },
  "Takliflar": { ru: "Предложения", en: "Offers" },
  "Tanlangan skinlar": { ru: "Выбранные скины", en: "Selected skins" },
  "Taqiqlangan": { ru: "Запрещено", en: "Prohibited" },
  "Tarixsiz": { ru: "Без истории", en: "No history" },
  "Tavsif 5000 belgidan oshmasin.": { ru: "Описание не должно превышать 5000 символов.", en: "Description must be under 5000 characters." },
  "Tavsif kiritilmagan.": { ru: "Описание не указано.", en: "No description provided." },
  "Tayyorlanmoqda": { ru: "Готовится", en: "Preparing" },
  "Tekshirilmoqda...": { ru: "Проверяется...", en: "Verifying..." },
  "Telegram bildirishnomalari": { ru: "Уведомления Telegram", en: "Telegram notifications" },
  "Telegram bot delivery faol.": { ru: "Доставка через Telegram-бота активна.", en: "Telegram bot delivery is active." },
  "Telegram tekshirilmoqda...": { ru: "Проверка Telegram...", en: "Checking Telegram..." },
  "Telegramni ochish": { ru: "Открыть Telegram", en: "Open Telegram" },
  "Top sotuvchilar": { ru: "Топ продавцов", en: "Top sellers" },
  "Top-up holatlari": { ru: "Статусы пополнений", en: "Top-up statuses" },
  "Topilmadi": { ru: "Не найдено", en: "Not found" },
  "Tranzaksiyalar tarixi": { ru: "История транзакций", en: "Transaction history" },
  "Tugashiga oz qolgan auksionlarni kuzating.": { ru: "Следите за аукционами, которые скоро закончатся.", en: "Track auctions that are ending soon." },
  "Vaziyatni batafsil yozing": { ru: "Опишите ситуацию подробно", en: "Describe the situation in detail" },
  "Xabar yozing...": { ru: "Напишите сообщение...", en: "Write a message..." },
  "Xabarlar": { ru: "Сообщения", en: "Messages" },
  "Xavfsiz Savdo": { ru: "Безопасная сделка", en: "Secure trade" },
  "Yakunlangan": { ru: "Завершено", en: "Completed" },
  "Yakunlangan savdo": { ru: "Завершённые сделки", en: "Completed trades" },
  "Yangilanmoqda...": { ru: "Обновляется...", en: "Updating..." },
  "Yaratilmoqda": { ru: "Создаётся", en: "Creating" },
  "Yashil-pushti gaming": { ru: "Зелёно-розовый гейминг", en: "Green-pink gaming" },
  "Yopilgan": { ru: "Закрыто", en: "Closed" },
  "Yordam chatini ochish": { ru: "Открыть чат поддержки", en: "Open support chat" },
  "Yuborish": { ru: "Отправить", en: "Send" },
  "Yuklanmoqda...": { ru: "Загрузка...", en: "Loading..." },
  "Aloqa": { ru: "Связь", en: "Contact" },
  "Aloqa sifati": { ru: "Качество связи", en: "Connection quality" },
  "Analitika": { ru: "Аналитика", en: "Analytics" },
  "Asl holat": { ru: "Исходный вид", en: "Original" },
  "Audit log": { ru: "Журнал аудита", en: "Audit log" },
  "Audit trail": { ru: "История аудита", en: "Audit trail" },
  "Auksion sanoq": { ru: "Отсчёт аукциона", en: "Auction countdown" },
  "Bahongiz": { ru: "Ваша оценка", en: "Your rating" },
  "Batafsil": { ru: "Подробнее", en: "Details" },
  "Bonus tizimi": { ru: "Бонусная система", en: "Bonus system" },
  "Boshqaruv": { ru: "Управление", en: "Management" },
  "Bosqichma-bosqich": { ru: "Пошагово", en: "Step by step" },
  "Broadcast xabar": { ru: "Массовая рассылка", en: "Broadcast message" },
  "Buyurtma raqami": { ru: "Номер заказа", en: "Order number" },
  "Chek holati": { ru: "Статус чека", en: "Receipt status" },
  "Chek monitoringi": { ru: "Мониторинг чеков", en: "Receipt monitoring" },
  "Conqueror tarixi": { ru: "История Conqueror", en: "Conqueror history" },
  "Daromad dinamikasi": { ru: "Динамика дохода", en: "Revenue dynamics" },
  "Deposit Review": { ru: "Проверка пополнения", en: "Deposit review" },
  "Emoji": { ru: "Эмодзи", en: "Emoji" },
  "Galereyani yopish": { ru: "Закрыть галерею", en: "Close gallery" },
  "Hamyon": { ru: "Кошелёк", en: "Wallet" },
  "Ichki chat": { ru: "Внутренний чат", en: "Internal chat" },
  "Inferno kafolat": { ru: "Гарантия Inferno", en: "Inferno guarantee" },
  "Inferno market": { ru: "Inferno маркет", en: "Inferno market" },
  "Ishonch markazi": { ru: "Центр доверия", en: "Trust center" },
  "Ism Familiya": { ru: "Имя Фамилия", en: "Full name" },
  "Javob": { ru: "Ответ", en: "Answer" },
  "Kabinet": { ru: "Кабинет", en: "Dashboard" },
  "Kafolat markazi": { ru: "Центр гарантий", en: "Guarantee center" },
  "Keyingi": { ru: "Далее", en: "Next" },
  "Kod nusxalandi": { ru: "Код скопирован", en: "Code copied" },
  "Kunlik faollik": { ru: "Дневная активность", en: "Daily activity" },
  "Language": { ru: "Язык", en: "Language" },
  "Localization desk": { ru: "Локализация", en: "Localization desk" },
  "Login/parolni faqat platformadagi kafolat jarayoni orqali topshiring.": { ru: "Передавайте логин/пароль только через гарантийный процесс платформы.", en: "Share the login/password only through the platform guarantee process." },
  "Maqsadga yetdi": { ru: "Цель достигнута", en: "Goal reached" },
  "Menyu": { ru: "Меню", en: "Menu" },
  "Moderation desk": { ru: "Модерация", en: "Moderation desk" },
  "Moderatsiya navbati": { ru: "Очередь модерации", en: "Moderation queue" },
  "Moliyaviy markaz": { ru: "Финансовый центр", en: "Finance center" },
  "Navigation": { ru: "Навигация", en: "Navigation" },
  "Nizo sababi": { ru: "Причина спора", en: "Dispute reason" },
  "Nizo yopildi": { ru: "Спор закрыт", en: "Dispute closed" },
  "Nomi": { ru: "Название", en: "Name" },
  "Nusxa": { ru: "Копия", en: "Copy" },
  "Oldingi": { ru: "Назад", en: "Previous" },
  "Orqaga": { ru: "Назад", en: "Back" },
  "O‘chirildi": { ru: "Удалено", en: "Deleted" },
  "Page Not Found": { ru: "Страница не найдена", en: "Page Not Found" },
  "It may have been moved or deleted.": { ru: "Возможно, она была перемещена или удалена.", en: "It may have been moved or deleted." },
  "Sorry, the page you are looking for doesn't exist.": { ru: "Извините, запрашиваемая страница не существует.", en: "Sorry, the page you are looking for doesn't exist." },
  "An unexpected error occurred.": { ru: "Произошла непредвиденная ошибка.", en: "An unexpected error occurred." },
  "Go Home": { ru: "На главную", en: "Go Home" },
  "Reload Page": { ru: "Перезагрузить", en: "Reload Page" },
  "Payout izohi": { ru: "Комментарий к выплате", en: "Payout note" },
  "Payout queue": { ru: "Очередь выплат", en: "Payout queue" },
  "Pro Tools": { ru: "Pro инструменты", en: "Pro Tools" },
  "Qaror izohi...": { ru: "Комментарий к решению...", en: "Decision note..." },
  "Qaytish": { ru: "Вернуться", en: "Back" },
  "Queue": { ru: "Очередь", en: "Queue" },
  "Referral dasturi": { ru: "Реферальная программа", en: "Referral program" },
  "Referral havolasi nusxalandi": { ru: "Реферальная ссылка скопирована", en: "Referral link copied" },
  "Referral kodi avtomatik tekshirilmadi. Profil orqali qayta urinib ko‘ring.": { ru: "Реферальный код не проверен автоматически. Попробуйте ещё раз через профиль.", en: "Referral code was not verified automatically. Try again from the profile." },
  "Referral kodini ishlatish": { ru: "Использовать реферальный код", en: "Use referral code" },
  "Referral kodini nusxalash": { ru: "Скопировать реферальный код", en: "Copy referral code" },
  "Sabab:": { ru: "Причина:", en: "Reason:" },
  "Safety desk": { ru: "Безопасность", en: "Safety desk" },
  "Savol": { ru: "Вопрос", en: "Question" },
  "Sharh qoldirish": { ru: "Оставить отзыв", en: "Leave a review" },
  "Sign in": { ru: "Войти", en: "Sign in" },
  "Sign in to continue": { ru: "Войдите, чтобы продолжить", en: "Sign in to continue" },
  "Sign out": { ru: "Выйти", en: "Sign out" },
  "Soon": { ru: "Скоро", en: "Soon" },
  "Summa, masalan 100000": { ru: "Сумма, например 100000", en: "Amount, e.g. 100000" },
  "Support & FAQ": { ru: "Поддержка и FAQ", en: "Support & FAQ" },
  "Surat": { ru: "Фото", en: "Photo" },
  "Tarjima asl holatiga qaytarildi": { ru: "Перевод возвращён к исходному", en: "Translation reset to original" },
  "Tarjimalar yuklanmoqda...": { ru: "Переводы загружаются...", en: "Loading translations..." },
  "Tavsif": { ru: "Описание", en: "Description" },
  "Tavsiya qidirilmoqda...": { ru: "Идёт поиск рекомендаций...", en: "Searching suggestions..." },
  "Tekshiruv navbati": { ru: "Очередь проверки", en: "Review queue" },
  "Tekshiruvda": { ru: "На проверке", en: "Under review" },
  "Telefon": { ru: "Телефон", en: "Phone" },
  "Telefon raqam orqali kirish": { ru: "Вход по номеру телефона", en: "Sign in with phone number" },
  "Telegram ulashish oynasi ochildi": { ru: "Окно «Поделиться» в Telegram открыто", en: "Telegram share window opened" },
  "Telegramda ulashish": { ru: "Поделиться в Telegram", en: "Share on Telegram" },
  "Toggle navigation": { ru: "Показать меню", en: "Toggle navigation" },
  "Trust desk": { ru: "Центр доверия", en: "Trust desk" },
  "Ulashish": { ru: "Поделиться", en: "Share" },
  "Umumiy taqsimot": { ru: "Общее распределение", en: "Overall distribution" },
  "Wallet": { ru: "Кошелёк", en: "Wallet" },
  "Wallet review": { ru: "Проверка кошелька", en: "Wallet review" },
  "Watchlist": { ru: "Список отслеживания", en: "Watchlist" },
  "Yangilash": { ru: "Обновить", en: "Refresh" },
  "Yashirish": { ru: "Скрыть", en: "Hide" },
  "Yechib olish navbati": { ru: "Очередь выводов", en: "Withdrawal queue" },
  "Yordam markazi": { ru: "Центр помощи", en: "Help center" },
  "24/7 ONLAYN": { ru: "24/7 ОНЛАЙН", en: "24/7 ONLINE" },
  "ISHONCHLI": { ru: "НАДЁЖНО", en: "TRUSTED" },
  "Kirishdan so": { ru: "После входа", en: "After sign-in" },
  "Tarix": { ru: "История", en: "History" },
  "Sharh": { ru: "Отзыв", en: "Review" },
  "Xabar": { ru: "Сообщение", en: "Message" },
  "O‘rtacha chek": { ru: "Средний чек", en: "Average order value" },
  "E’lon": { ru: "Объявление", en: "Listing" },
  "Tezkor yordam": { ru: "Быстрая помощь", en: "Quick help" },
  "Skin": { ru: "Скин", en: "Skin" },
  "Karta raqami": { ru: "Номер карты", en: "Card number" },
  "Rasm ochilmadi": { ru: "Не удалось открыть изображение", en: "Could not open image" },
  "Buyurtma qaytarimi": { ru: "Возврат по заказу", en: "Order refund" },
  "Rad etildi": { ru: "Отклонено", en: "Rejected" },
  "Nizo": { ru: "Спор", en: "Dispute" },
  "Foydalanuvchi": { ru: "Пользователь", en: "User" },
  "Bildirishnoma yoqildi": { ru: "Уведомления включены", en: "Notifications enabled" },
  "Tarjima xatosini belgilash": { ru: "Отметить ошибку перевода", en: "Report a translation issue" },
  "Noto‘g‘ri yozuvni bosing": { ru: "Нажмите на неверный текст", en: "Tap the incorrect text" },
  "Tarjima xatosi": { ru: "Ошибка перевода", en: "Translation issue" },
  "To‘g‘ri variantni yozing (ixtiyoriy)": { ru: "Напишите правильный вариант (необязательно)", en: "Suggest the correct wording (optional)" },
  "Bu joyda matn topilmadi": { ru: "Здесь текст не найден", en: "No text found here" },
  "Rahmat! Tarjima xatosi adminga yuborildi": { ru: "Спасибо! Ошибка перевода отправлена админу", en: "Thanks! The translation issue was sent to the admin" },
  "Yuborib bo‘lmadi, keyinroq urinib ko‘ring": { ru: "Не удалось отправить, попробуйте позже", en: "Could not send, please try again later" },
  "Tashqi Telegram bot push xabarlari uchun token sozlanishi kerak; hozircha tizim in-app bildirishnomalarni xavfsiz saqlaydi.": { ru: "Для push-уведомлений внешнего Telegram-бота нужен токен; пока система безопасно хранит уведомления внутри приложения.", en: "An external Telegram bot token is required for push notifications; for now the system stores in-app notifications securely." },
  "Filtr saqlandi": { ru: "Фильтр сохранён", en: "Filter saved" },
  "Avval kamida bitta filtr tanlang": { ru: "Сначала выберите хотя бы один фильтр", en: "Select at least one filter first" },
  "Filtr yuklandi": { ru: "Фильтр загружен", en: "Filter loaded" },
  "Filtri saqlash": { ru: "Сохранить фильтр", en: "Save filter" },
};
