export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  adminPayoutCardNumber: process.env.ADMIN_PAYOUT_CARD_NUMBER ?? "",
  adminPayoutCardHolder: process.env.ADMIN_PAYOUT_CARD_HOLDER ?? "",
  adminUzcardNumber: process.env.ADMIN_UZCARD_NUMBER ?? "5614 6805 7716 7758",
  adminVisaNumber: process.env.ADMIN_VISA_NUMBER ?? "4067 0700 0330 3687",
  adminCardHolder: process.env.ADMIN_CARD_HOLDER ?? "ALIMARDONOV U.",
};
